config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'top/main'
  resources :users
  root 'users#index'
  get 'users/new'
  post 'users/create'
  delete 'users/:id', to: 'users#destroy'
  
  get 'tweets/index'
  get 'tweets/new'
  post 'tweets/create'
  delete '/tweets/:id', to: 'tweets#destroy'
  
  post 'top/login'
  get 'top/logout'
  
  post 'likes/create'
  delete '/likes/:id', to: 'likes#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :like_users,
    through: :likes,
    source: :user
    
    validates :message, presence: true
    
    def like(user)
      likes.create(user_id: user.id)
    end
  
    def unlike(user)
      likes.find_by(user_id: user.id).destroy
    end
      
    def liked?(user) #いいね済みか調べる(true / false)
      like_users.include?(user)
    end
    
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :like_tweets,
    through: :likes,
    source: :tweet
    
    validates :password, presence: true, confirmation: true
    validates :uid, presence: true
    
    attr_accessor :password, :password_confirmation
    
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def L5
      session[:c] ||= 0
      session[:c] = session[:c].to_i + 1
      render plain: session[:c]
    end
    
    private
    def current_user
      if session[:login_uid]
        User.find_by(uid: session[:login_uid])
      end
    end
    helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
      tweet.like(current_user)
    end
    redirect_to tweets_index_url
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.liked?(current_user)
      tweet.unlike(current_user)
    end
    redirect_to tweets_index_url
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if current_user 
      redirect_to tweets_index_url
    else
      render 'login.html.erb'
    end
  end
  
  def login
    uid = params[:uid]
    pass = params[:pass]
    user = User.find_by(uid: uid)
    if user == nil
      session[:login_uid] = nil
      return 'ログインに失敗しました'
    else
      if BCrypt::Password.new(user.pass) == pass
        session[:login_uid] = uid
        redirect_to tweets_index_url
      else
        p user
        session[:login_uid] = nil
        return 'ログインに失敗しました'
      end
      
    end
  end
  
  def logout
    session[:login_uid] = nil
    redirect_to top_main_url
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    if current_user
      @tweets = Tweet.all
      
    else
      render 'top/login.html.erb'
    end
    
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    tweet = Tweet.new(message: params[:tweet][:message])
    user = User.find_by(uid: session[:login_uid])
    user.tweets << tweet
    tweet.user = user
    if tweet.save
      redirect_to tweets_index_url
    else
      return HttpResponse("ツイートの投稿に失敗しました")
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to tweets_index_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    if User.find_by(uid: params[:user][:uid])
      flash[:notice] = 'そのユーザーIDはすでに使われています'
      redirect_to users_new_url
    else
      uid = params[:user][:uid]
      password = params[:user][:password]
      password_confirmation = params[:user][:password_confirmation]
      user = User.new(uid: uid, password: password,
      password_confirmation: password_confirmation)
      if user.save
        redirect_to root_path
      else
        flash[:notice] = 'パスワードが一致していません'
        redirect_to users_new_url
      end
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/top/login.html.erb
<h1>ログイン</h1>

<%= form_tag '/top/login' , method: :post do %>
<%= label_tag :uid, 'ユーザーID' %>
<%= text_field_tag :uid %><br>
<%= label_tag :pass, 'パスワード' %>
<%= text_field_tag :pass %><br>
<%= submit_tag 'ログイン' ,class: "btn_edit" %>


<%end%>

<br>
<%= link_to 'ユーザー登録', users_new_url %><br>
<%= link_to 'ユーザー一覧', root_path %>

app/views/top/login_form.html.erb
top/login

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>

app/views/tweets/index.html.erb
<h1>Tweets一覧</h1>

<% @tweets.each do |t| %>
    <%= t.message %><br>
    投稿者：<%= t.user.uid %>

    <% if Like.find_by(tweet_id: t.id) %>

        <%= link_to 'いいね削除', "/likes/#{t.id}", method: :delete %>
    <% else %>
        <%= link_to 'いいね', likes_create_path(tweet_id: t.id), method: :post %>
    <%end%>
    <br>
    <%= link_to 'ツイート削除', "/tweets/#{t.id}", method: :delete %>
    <br><br>
<% end %>

<br>
<%= link_to 'ツイートする', 'new' %><br>
<%= link_to 'ログアウト', top_logout_url %>

app/views/tweets/new.html.erb
<h1>Tweet作成</h1>

<%= form_for @tweet , url: {action: :create} do |f| %>
<%= f.label :message, 'メッセージ' %>
<%= f.text_field :message %><br>
<%= f.submit '登録' ,class: "btn_edit" %>


<%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% @users.each do |u| %>
    <%= u.uid %>
    <%= link_to '削除', "users/#{u.id}", method: :delete %>
    <br>
<% end %>

<br>
<%= link_to 'ユーザー登録', 'users/new' %><br>
<%= link_to 'ログインする', 'top/main' %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<%= form_for @user , url: {action: :create} do |f| %>
<%= f.label :uid, 'ユーザーID' %>
<%= f.text_field :uid %><br>
<%= f.label :password, 'パスワード' %>
<%= f.text_field :password %><br>
<%= f.label :password_confirmation, 'パスワードの確認' %>
<%= f.text_field :password_confirmation %><br>
<%= f.submit '登録' ,class: "btn_edit" %>


<%end%><br>
<%= link_to '戻る', top_main_url %>